/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApiSchema {
  Todo: Todo;
  Reminder: Reminder;
  ShoppingItem: ShoppingItem;
}
export interface Todo {
  id: string;
  user_id?: string;
  text: string;
  completed: boolean;
  priority: string;
  due_date?: string;
  created_at: string;
  completed_at?: string;
}
export interface Reminder {
  id: string;
  user_id?: string;
  text: string;
  remind_at: string;
  dismissed: boolean;
  created_at: string;
  dismissed_at?: string;
}
export interface ShoppingItem {
  id: string;
  user_id?: string;
  item: string;
  quantity?: string;
  created_at: string;
}
